name: Unit Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [Release, Debug]
        profile:
          - compiler: g++
            filename: ./conan/gcc.profile
          - compiler: clang++
            filename: ./conan/clang.profile
    steps:
      - uses: actions/checkout@v3
      - uses: turtlebrowser/get-conan@main
      - run: sudo apt-get install -y autopoint
      - run: conan install . -pr:b=${{ matrix.profile.filename }} -pr:h=${{ matrix.profile.filename }} --build=missing
      - run: cmake . -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_COMPILER=${{ matrix.profile.compiler }}
      - run: cmake --build .
      - run: ./nonrec-test
      - run: ./nonrec-bench
