name: Unit Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [Release, Debug]
    steps:
      - uses: actions/checkout@v3
      - uses: turtlebrowser/get-conan@main
      - run: sudo apt-get install -y autopoint
      - run: conan install . -pr:b=default --build=missing
      - run: cmake . -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - run: cmake --build .
      - run: ./nonrec-test

