name: Unit Tests
on: [push]
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: turtlebrowser/get-conan@main
      - run: conan install . --profile default --build=missing
  build:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - run: pwd
      - run: ls
      - run: cmake .
      - run: cmake --build .
  run-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: ./nonrec-test
